### ISSUE TITLE
Do You Mind if I Embed in My Site?

### ISSUE THREAD

**Issue by ghost** [cpdt/r2browser#1]
Would you mind if I were to embed or make a whole page with this on my site? Obviously, it would have your name at the bottom left like it already does. Just wanted to ask before I did something you didn't like. Also, I may change the bg to green if you don't mind lol.

**Comment by cpdt** [comment]
Yeah feel free, you can do whatever with it, just make sure you follow the terms set in [the license](https://github.com/cpdt/r2browser/blob/main/LICENSE) :)

**Comment by ghost** [comment]
uh okie lemme check...

**Comment by ghost** [comment]
alright, thanks. Just wanted to check.
